### ISSUE TITLE
background for selected text

### ISSUE THREAD

**Issue by rcrooks** [KStew1017/sea-glass-vscode-color-theme#1]
Hi @KStew1017 - thanks for a really nice theme. Just a small suggestion: could you lighten the background color for selected text just a little so that it's easy to see?

Thanks for considering.

**Comment by KStew1017** [comment]
Hey @rcrooks thanks for the feedback! That was something I noticed also, and I agree it should be more visible. I'll get that fixed by the end of today.

**Comment by rcrooks** [comment]
That's awesome - thanks Kyle!

**Comment by KStew1017** [comment]
@rcrooks Just updated it, let me know how it is.

**Comment by rcrooks** [comment]
Thanks! Yes, it’s fine now.
